### ISSUE TITLE
How do you deal with the renewal of qualification traces?

### ISSUE THREAD

**Issue by qiaoxianfeng** [brett-daley/dqn-lambda#12]
After using the deep neural network to approximate the Q table, how do you deal with the update of the qualification trace?

**Comment by brett-daley** [comment]
Hi @qiaoxianfeng, I'm not sure but I think you are asking about the refresh procedure in the replay memory. This method is called every 10,000 timesteps to update the λ-returns using the latest Q-value estimates:

https://github.com/brett-daley/dqn-lambda/blob/e1bbbaecf18cdc9f8edfbef8075b988a61e21235/dqn.py#L133-L134

**Comment by qiaoxianfeng** [comment]
> 嗨@qxiaoxiao，我确定，但我想你是在搜索方法内存中的刷新程序。此每10,000个时间步调用一次，以使用最新的Q值更新λ回报：
> 
> https://github.com/brett-daley/dqn-lambda/blob/e1bbbaecf18cdc9f8edfbef8075b988a61e21235/dqn.py#L133-L134

Thank you for your reply.
